services:
  database:
    container_name: octogriffin_database
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: octogriffin_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASS}'
    ports:
      - '5050:80'
    depends_on:
      - database

volumes:
  db_data:
